spring.application.name=springboot.3.4.4.base

###############################################################################
## 서비스 포트 설정
###############################################################################
# HTTPS 포트 설정
server.port=80

### JSP
#spring.mvc.view.prefix=/WEB-INF/views/jsp/
#spring.mvc.view.suffix=.jsp

#spring.thymeleaf.enabled=true
spring.thymeleaf.view-names=views/*
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
#수정사항을 바로 반영하기 위해 false 로 설정한다.
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true