spring.application.name=epicit.sboot344.prototype


###############################################################################
## 서비스 포트 설정
###############################################################################
# HTTPS 포트 설정
server.port=80
server.http2.enabled=true

spring.web.resources.static-locations=classpath:static

### =========================================================================== ###

# devtools 설정
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# 정적 자원 캐시 완전히 비활성화
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.max-age=0
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.web.resources.chain.enabled=false

# restart 안 되도록 제외 설정
spring.devtools.restart.exclude=static/**,public/**,resources/**,META-INF/**

### =========================================================================== ###

### JSP
#spring.mvc.view.prefix=/WEB-INF/views/jsp/
#spring.mvc.view.suffix=.jsp


#수정사항을 바로 반영하기 위해 false 로 설정한다.
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
#spring.thymeleaf.view-names=views/*


# DataSource
#spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.url=jdbc:log4jdbc:sqlite:./src/db/Mojito.Maldive.sqlite
#spring.datasource.username=root
#spring.datasource.password=1234
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.idle-timeout=10000


# Mybatis Settings
mybatis.config-location=classpath:config/mybatis/mybatis-config.xml
mybatis.mapper-locations=classpath:config/mybatis/mapper/**/*.xml